### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by lazydino** [nasa/openmct-demo#8]
"npm install" complains "reference ea77e014b8d82b04f938ec3f845ecedc5c200fa7 is not a tree"

Is github:nasa/openmct#ea77e014b8d82b04f938ec3f845ecedc5c200fa7 in the package.json valid?

**Comment by tblaisde** [comment]
Also having this issue.

**Comment by Srokap** [comment]
I was able to run install correctly with `github:nasa/openmct#98c8e19d933694ae69a6e9b60769f45a3e8cb9a1`

**Comment by tkotisis** [comment]
Using `github:nasa/openmct#98c8e19d933694ae69a6e9b60769f45a3e8cb9a1` and node v14.18.0 (latest lts) `npm install` fails with the following error:

> npm ERR! prepareGitDep bower moment-timezone#^0.5.13           invalid-meta for:/tmp/tkotisis/bower/87f48d7c4646ec50a0339e33158bdd33-17247-2Nh997/bower.json
npm ERR! prepareGitDep bower moment-timezone#^0.5.13           invalid-meta The "main" field cannot contain minified files
npm ERR! prepareGitDep fs.js:40
npm ERR! prepareGitDep } = primordials;
npm ERR! prepareGitDep     ^
npm ERR! prepareGitDep
npm ERR! prepareGitDep ReferenceError: primordials is not defined
npm ERR! prepareGitDep     at fs.js:40:5
npm ERR! prepareGitDep     at req_ (/home/tkotisis/.npm/_cacache/tmp/git-clone-7ac66fcf/node_modules/natives/index.js:143:24)
npm ERR! prepareGitDep     at Object.req [as require] (/home/tkotisis/.npm/_cacache/tmp/git-clone-7ac66fcf/node_modules/natives/index.js:55:10)
npm ERR! prepareGitDep     at Object.<anonymous> (/home/tkotisis/.npm/_cacache/tmp/git-clone-7ac66fcf/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
npm ERR! prepareGitDep     at Module._compile (/home/tkotisis/.npm/_cacache/tmp/git-clone-7ac66fcf/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
npm ERR! prepareGitDep     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! prepareGitDep     at Module.load (internal/modules/cjs/loader.js:950:32)
npm ERR! prepareGitDep     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
npm ERR! prepareGitDep     at Module.require (internal/modules/cjs/loader.js:974:19)
npm ERR! prepareGitDep     at require (/home/tkotisis/.npm/_cacache/tmp/git-clone-7ac66fcf/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! openmct@0.14.0-SNAPSHOT prepare: `node ./node_modules/bower/bin/bower install && node ./node_modules/gulp/bin/gulp.js install`
npm ERR! prepareGitDep npm ERR! Exit status 1
